// Aggregated component-API map. Auto-generated by extract-api.mjs during
// Chunk 07. Used by the Code tab on the component page renderer.

import type { ComponentApi } from './types';

import { badgeApi } from './badge';
import { breadcrumbApi } from './breadcrumb';
import { buttonApi } from './button';
import { checkboxApi } from './checkbox';
import { chipApi } from './chip';
import { comboboxApi } from './combobox';
import { dataTableApi } from './data-table';
import { dataViewApi } from './data-view';
import { datePickerApi } from './date-picker';
import { dialogApi } from './dialog';
import { dividerApi } from './divider';
import { dropdownApi } from './dropdown';
import { iconWrapperApi } from './icon-wrapper';
import { labelApi } from './label';
import { linkApi } from './link';
import { listApi } from './list';
import { navHeaderApi } from './nav-header';
import { navVerticalApi } from './nav-vertical';
import { notificationApi } from './notification';
import { paginationApi } from './pagination';
import { radioApi } from './radio';
import { searchApi } from './search';
import { spacerApi } from './spacer';
import { tabsApi } from './tabs';
import { textAreaApi } from './text-area';
import { textInputApi } from './text-input';
import { tileApi } from './tile';
import { toggleApi } from './toggle';
import { tooltipApi } from './tooltip';

export const COMPONENT_API: Record<string, ComponentApi> = {
  'badge': badgeApi,
  'breadcrumb': breadcrumbApi,
  'button': buttonApi,
  'checkbox': checkboxApi,
  'chip': chipApi,
  'combobox': comboboxApi,
  'data-table': dataTableApi,
  'data-view': dataViewApi,
  'date-picker': datePickerApi,
  'dialog': dialogApi,
  'divider': dividerApi,
  'dropdown': dropdownApi,
  'icon-wrapper': iconWrapperApi,
  'label': labelApi,
  'link': linkApi,
  'list': listApi,
  'nav-header': navHeaderApi,
  'nav-vertical': navVerticalApi,
  'notification': notificationApi,
  'pagination': paginationApi,
  'radio': radioApi,
  'search': searchApi,
  'spacer': spacerApi,
  'tabs': tabsApi,
  'text-area': textAreaApi,
  'text-input': textInputApi,
  'tile': tileApi,
  'toggle': toggleApi,
  'tooltip': tooltipApi,
};

export type { ComponentApi } from './types';
