// AUTO-GENERATED — do not edit by hand.
//
// Run `npm run gen:types` to regenerate from uds/schemas/*.schema.json.
// Source schemas: version.schema.json, components-manifest.schema.json, spec.schema.json, status.schema.json, changelog.schema.json, impl.schema.json, manifest.schema.json, figmanotes.schema.json
//
// The pure data loaders in lib/uds-data.ts re-export these with shorter
// aliases as the public surface of the UDS data layer; consumer code
// should import from there, not from this file directly.

// ============================================================================
// version.schema.json
// ============================================================================

/**
 * Top-level UDS release metadata. Lives at uds/version.json.
 */
export interface UDSVersion {
  $schema?: string;
  /**
   * UDS release identifier, e.g. '0.3'.
   */
  version: string;
  /**
   * ISO date the release was tagged (YYYY-MM-DD).
   */
  released?: string;
  /**
   * Which spec.schema.json version this release conforms to. Renderer can branch on this when reading historical snapshots.
   */
  schemaVersion: number;
  [k: string]: unknown;
}

// ============================================================================
// components-manifest.schema.json
// ============================================================================

/**
 * List of all components in this UDS release. The single source of truth for 'which components exist'. Generated by scripts/aggregate-components.sh — do not edit by hand. Used by the Next.js docs app to know which component pages to generate and render.
 */
export interface UDSComponentsManifest {
  $schema?: string;
  /**
   * Components in display order (earliest UDS version first, alphabetical tiebreak)
   */
  components: {
    /**
     * Component folder name and route segment
     */
    id: string;
    /**
     * Display title (from spec.json)
     */
    title: string;
    /**
     * First UDS version this component appeared in
     */
    since: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

// ============================================================================
// spec.schema.json
// ============================================================================

/**
 * Schema for per-component spec.json files. Every field is optional — the renderer hides sections where data is missing or empty. See uds/components/<id>/spec.json for examples.
 */
export interface UDSComponentSpecSchema {
  /**
   * Path to this schema file (../../schemas/spec.schema.json)
   */
  $schema?: string;
  /**
   * Component ID matching folder name and route segment
   */
  component: string;
  title?: string;
  /**
   * One-paragraph summary of the component's purpose
   */
  description?: string;
  whenToUse?: string;
  /**
   * Include suggested alternative component
   */
  whenNotToUse?: string;
  /**
   * Checklist items. This IS the ship checklist — when all items are verified (design + dev), the component can move to Production Ready.
   */
  acceptanceCriteria?: string[];
  dependencies?: {
    /**
     * e.g. uds/components/button/button.css
     */
    css?: string[];
    /**
     * e.g. uds/components/dropdown/dropdown.js
     */
    js?: string[];
    /**
     * Groups of CSS custom properties the component uses, e.g. { Surface: [...], Typography: [...] }
     */
    tokens?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Web component attributes/props the Storybook implementation should support.
   */
  props?: {
    name: string;
    /**
     * 'string' | 'boolean' | 'number' | 'enum' | 'object'
     */
    type: string;
    default?: string | boolean | number | null;
    required?: boolean;
    /**
     * For type=enum, the allowed values
     */
    enum?: string[];
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Custom events the component should dispatch.
   */
  events?: {
    name: string;
    description?: string;
    /**
     * Event detail shape
     */
    payload?: string;
    [k: string]: unknown;
  }[];
  /**
   * Named slots or content regions inside the component.
   */
  slots?: {
    name: string;
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Every interactive state the component supports. Include 'not applicable' entries to make coverage explicit.
   */
  states?: {
    /**
     * default | hover | active | focus | focus-visible | selected | disabled | error | loading | empty | not-applicable
     */
    name: string;
    description?: string;
    /**
     * Whether this state has a distinct visual treatment
     */
    hasVisual?: boolean;
    [k: string]: unknown;
  }[];
  /**
   * Character limits, truncation, empty state copy, error tone
   */
  contentGuidelines?: string;
  /**
   * Component IDs (e.g. 'dialog', 'button')
   */
  commonlyPairedWith?: string[];
  dosDonts?: {
    dos?: string[];
    donts?: string[];
    [k: string]: unknown;
  };
  accessibility?: {
    keyboard?: {
      key: string;
      action: string;
      [k: string]: unknown;
    }[];
    screenReader?: {
      trigger: string;
      announcement: string;
      [k: string]: unknown;
    }[];
    wcag?: {
      /**
       * e.g. '2.1.1'
       */
      criterion: string;
      /**
       * A | AA | AAA
       */
      level: string;
      howMet?: string;
      [k: string]: unknown;
    }[];
    contrast?: {
      /**
       * Token name or hex
       */
      foreground?: string;
      background?: string;
      ratio?: number;
      /**
       * AA | AAA | fail
       */
      passes?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  knownIssues?: string[];
  /**
   * Component-specific performance notes. Leave null unless there are specific concerns (e.g. virtualize Data Table at 200+ rows).
   */
  performance?: string | null;
  /**
   * DEFERRED: UDS has no motion tokens yet. Leave null.
   */
  motion?: string | null;
  /**
   * DEFERRED: UDS has no breakpoint tokens yet. Leave null.
   */
  responsive?: string | null;
  /**
   * Where this component fits in page layout (primary action vs secondary, etc.)
   */
  visualHierarchy?: string | null;
  /**
   * Appearance differences between compact vs comfortable density
   */
  densityBehavior?: string | null;
  owner?: {
    designer?: string;
    developer?: string;
    [k: string]: unknown;
  };
  /**
   * When true, hide from sidebar/routing on production. Show with ?draft=1.
   */
  draft?: boolean;
  /**
   * Deep-link to specific variant node in Figma. If null, the renderer falls back to figmaPageNodeId.
   */
  figmaNodeId?: string | null;
  /**
   * Deep-link to the component's page-level node in the UDS Components Figma file. Used as fallback when figmaNodeId is null.
   */
  figmaPageNodeId?: string | null;
  /**
   * Storybook story path, e.g. 'components-button--primary'. If null, falls back to the Storybook home.
   */
  storybookSlug?: string | null;
  /**
   * Declarative pointer to an example file used by the Implementation Reference panel.
   */
  implReference?: {
    /**
     * ID of an entry in this component's examples/manifest.json
     */
    exampleId?: string;
    [k: string]: unknown;
  } | null;
  /**
   * Factory build provenance — which version of the component factory produced the Figma source this spec was synced from. Metadata only; not rendered. Written by sync-figma-component-spec / uds-updated from the component-set stamp. See .cursor/rules/uds-factory-versioning.mdc.
   */
  provenance?: {
    /**
     * Factory build vintage (YYYY.MM.DD.N) that built the Figma source — the date the factory's output last changed, NOT the build date.
     */
    factoryVersion?: string;
    /**
     * Contract-block format version, e.g. 'v1'.
     */
    contractVersion?: string;
    /**
     * Factory run id, e.g. 'metric-card-2026-06-04'.
     */
    runId?: string;
    /**
     * Date the component was actually built (YYYY-MM-DD); distinct from factoryVersion.
     */
    builtAt?: string;
    /**
     * Figma component-set node id the component was synced from (optional).
     */
    landedFrom?: string;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}

// ============================================================================
// status.schema.json
// ============================================================================

/**
 * Lifecycle status for a single component. Lives at uds/components/<id>/status.json.
 */
export interface UDSComponentStatus {
  $schema?: string;
  /**
   * Current lifecycle status.
   */
  current: 'placeholder' | 'blocked' | 'in-progress' | 'review' | 'production' | 'deprecated';
  /**
   * UDS version in which the current status was entered. e.g. '0.1', '0.3'.
   */
  since: string;
  /**
   * Audit trail. release.sh appends here on status changes.
   */
  history?: {
    version: string;
    status: 'placeholder' | 'blocked' | 'in-progress' | 'review' | 'production' | 'deprecated';
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

// ============================================================================
// changelog.schema.json
// ============================================================================

/**
 * Per-component changelog. Source of truth — release.sh aggregates these into uds/CHANGELOG.json. Lives at uds/components/<id>/changelog.json.
 */
export interface UDSComponentChangelog {
  $schema?: string;
  /**
   * UDS version this component first appeared in. Cross-validated against status.json.history[0].version.
   */
  addedIn: string;
  /**
   * All changes ever, oldest first (matches global CHANGELOG convention).
   */
  entries: {
    /**
     * UDS version this entry was shipped in.
     */
    version: string;
    /**
     * Type of change.
     */
    type: 'added' | 'changed' | 'fixed' | 'deprecated' | 'removed';
    /**
     * Description of the change.
     */
    text: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

// ============================================================================
// impl.schema.json
// ============================================================================

/**
 * Per-component impl.json file. Powers the Implementation Reference details on the Code tab: example HTML, optional behavior notes, and categorized design-token references.
 */
export interface UDSComponentImplementationReference {
  $schema?: string;
  /**
   * Legacy-compatible behavior function name. Null for current Web Component implementations unless an archived component payload still references a function.
   */
  jsFunc?: string | null;
  /**
   * Legacy-compatible path to the JS file containing jsFunc, relative to uds-docs/. Null for current Web Component implementations.
   */
  jsFile?: string | null;
  /**
   * CSS custom properties the component depends on, grouped by category. Common groups: Color, Font, Space, Border. Each group is an array of token names like '--uds-color-surface-main'.
   */
  tokens?: {
    [k: string]: string[];
  };
  /**
   * The full HTML body shown in the 'Component File' tab and bundled into the ZIP download. Includes <!DOCTYPE>, <head>, <link> tags, and component example markup. Plain string — no template substitution.
   */
  html?: string;
  [k: string]: unknown;
}

// ============================================================================
// manifest.schema.json
// ============================================================================

/**
 * Declares the example HTML files for a component, what shows in docs, and what's eligible for the Demo Builder. Lives at uds/components/<id>/examples/manifest.json.
 */
export interface UDSComponentExamplesManifest {
  $schema?: string;
  examples: {
    /**
     * Stable identifier for this example, used by implReference, Examples tab linking, and Demo Builder selection.
     */
    id: string;
    /**
     * Path to the HTML fragment, relative to this manifest. e.g. 'default.html'.
     */
    file: string;
    /**
     * Human-readable heading shown above the example on the docs page.
     */
    label?: string;
    /**
     * Optional caption shown below the heading.
     */
    description?: string;
    /**
     * Whether this example renders on the component's docs page Examples tab.
     */
    showInDocs?: boolean;
    /**
     * Demo Builder picks weighted-randomly among entries with demoWeight > 0. 0 excludes from Demo Builder.
     */
    demoWeight?: number;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

// ============================================================================
// figmanotes.schema.json
// ============================================================================

/**
 * Per-component open Figma findings surfaced by the figma-component-inspector — design questions, drift, explorations, and orphans that need designer attention. Lives at uds/components/<id>/figmanotes.json. Auto-pruned by the inspector on subsequent runs when the underlying condition is resolved (except kind=question, which is manual-only).
 */
export interface UDSComponentFigmaNotes {
  $schema?: string;
  /**
   * List of open Figma notes for this component. Empty list (or missing file) means no open notes — the Figma Notes tab will not render.
   */
  notes: {
    /**
     * Stable kebab-case identifier for this note. Used by auto-prune to match the same note across inspector runs (so a note doesn't get added twice). Examples: 'logo-pill-exploration', 'outline-true-variant', 'page-orphans'.
     */
    id: string;
    /**
     * Category for the inspector's auto-prune logic. new-in-figma = new Figma node that isn't wired into the canonical component yet. figma-orphan = node sits in Figma but no longer attached to the canonical tree. drift = Figma value and code value disagree on something measurable. question = open question that doesn't fit the others; auto-prune does not apply.
     */
    kind: 'new-in-figma' | 'figma-orphan' | 'drift' | 'question';
    /**
     * One-line headline in plain language. No jargon ('canonical contract', 'unattested-by-figma', 'variant matrix'). Aim for what a designer would write to a teammate.
     */
    title: string;
    /**
     * 1-3 plain sentences explaining what was observed and where. May reference layer names, but keep them inline rather than as separate fields.
     */
    summary: string;
    /**
     * Optional question to the designer / owner. Phrased as a question, e.g. 'Should the new logo replace the simple one, or sit alongside as a variant?' Omit if the note is purely informational.
     */
    decisionNeeded?: string;
    /**
     * Figma nodes referenced by this note. Used to deep-link from the UI and (for kinds that auto-prune) to check resolution on subsequent inspector runs.
     */
    figmaRefs?: {
      /**
       * Human-readable layer / component name as it appears in Figma.
       */
      name: string;
      /**
       * Figma node id, e.g. '6399:13744'. Used to construct the deep-link URL.
       */
      nodeId: string;
      [k: string]: unknown;
    }[];
    /**
     * Optional plain-language description of the condition that should auto-resolve this note. Examples: 'logo-pill becomes a nested instance in udc-nav-header', 'orphan dropdown is deleted from the nav-header Figma page'. Informational — the actual prune logic is in the inspector by kind.
     */
    autoPruneWhen?: string;
    /**
     * Which agent or human raised this note. Usually 'figma-component-inspector'. Defaults to 'figma-component-inspector' if omitted.
     */
    raisedBy?: string;
    /**
     * ISO 8601 date (YYYY-MM-DD) the note was first surfaced.
     */
    raisedOn: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
