#!/usr/bin/env bash
# scripts/regenerate-toolchain.sh
#
# Deterministically rebuilds .cursor/TOOLCHAIN.md from the YAML
# frontmatter of every .cursor/{rules,skills,agents}/* file. Always
# overwrites — no merging with the existing file.
#
# The static intro sections (Discipline, Sync check) are written from
# templates inside this script. The three table sections (Rules, Skills,
# Subagents) are generated fresh each run.
#
# Usage: bash scripts/regenerate-toolchain.sh
#
# Run after:
#   - Adding/removing/renaming a rule, skill, or subagent.
#   - Editing a frontmatter description or lastUpdated value.
#   - Running `bash scripts/seed-toolchain-timestamps.sh`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

OUTPUT=".cursor/TOOLCHAIN.md"

python3 - "$OUTPUT" <<'PYEOF'
import glob
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

OUTPUT = sys.argv[1]


def parse_frontmatter(path: Path) -> Tuple[Dict[str, str], str]:
    text = path.read_text()
    if not text.startswith('---\n'):
        return {}, text
    end = text.find('\n---\n', 4)
    if end == -1:
        return {}, text
    fm_text = text[4:end]
    body = text[end + 5:]
    fm: Dict[str, str] = {}
    current_key = None
    for line in fm_text.split('\n'):
        m = re.match(r'^([a-zA-Z][a-zA-Z0-9_]*):\s*(.*)$', line)
        if m:
            current_key = m.group(1)
            fm[current_key] = m.group(2).strip()
        elif current_key and line.strip():
            fm[current_key] += ' ' + line.strip()
    return fm, body


def shortdesc(d: str, maxlen: int = 140) -> str:
    d = re.sub(r'\s+', ' ', d.strip())
    if len(d) <= maxlen:
        return d
    return d[:maxlen].rsplit(' ', 1)[0] + '\u2026'


def row(p: Path, kind: str) -> str:
    fm, _ = parse_frontmatter(p)
    desc = shortdesc(fm.get('description', '_(missing description)_')).replace('|', '\\|')
    last = fm.get('lastUpdated', '_(missing)_')
    if kind == 'rule':
        link = f"[`{p.name}`](./rules/{p.name})"
    elif kind == 'skill':
        link = f"[`{p.parent.name}`](./skills/{p.parent.name}/SKILL.md)"
    else:
        link = f"[`{p.stem}`](./agents/{p.name})"
    return f"| {link} | `{last}` | {desc} |"


rules = sorted(Path('.').glob('.cursor/rules/*.mdc'))
skills = sorted(Path('.').glob('.cursor/skills/*/SKILL.md'))
agents = sorted(Path('.').glob('.cursor/agents/*.md'))

INTRO = """\
# Cursor Toolchain Index

Inventory of every Cursor rule, skill, and subagent in this repo, with
the ISO 8601 UTC timestamp of each file's most recent meaningful edit.
The agent reads this at session start to see at a glance what has
changed in the instruction layer.

This file is **regenerated by `bash scripts/regenerate-toolchain.sh`**
from the YAML frontmatter of every rule/skill/subagent file. Do not
hand-edit the tables below — your edits will be overwritten on the next
regeneration. Edit the source files' frontmatter (`description`,
`lastUpdated`) instead, then re-run the regenerator.

## Discipline

Whenever you edit any file under `.cursor/rules/`, `.cursor/skills/`,
or `.cursor/agents/`:

1. Bump that file's `lastUpdated:` in its YAML frontmatter to the current
   ISO 8601 UTC timestamp. Use the system `date` command \u2014 never guess:

   ```bash
   date -u +%Y-%m-%dT%H:%M:%SZ
   ```

2. Run `bash scripts/regenerate-toolchain.sh` to refresh this file.
3. If you added a new rule/skill/subagent, also add a row to
   `uds-docs/app/(site)/cursor-workflows/CursorWorkflowsClient.tsx` so
   `audit-agent-docs-currency.sh` passes.

CI enforces this via `scripts/audit-toolchain-currency.sh`, which fails
if any rule/skill/subagent file's git mtime is newer than its
`lastUpdated:` value or its row in this file is missing/stale. See
`.cursor/rules/uds-rule-discipline.mdc` for the full rule.

## Sync check

Before relying on anything below, confirm the local repo is current with
`origin/main`. The `sessionStart` Cursor hook at
`.cursor/hooks/sync-check.sh` runs `git fetch origin main` and writes
`.cursor/state/sync-status.json` (canonical) on every session start.
The `Phase 1: Verify sync state` step in `uds-master-preflight.mdc` is
the manual fallback when the hook hasn't run.

"""


def render() -> str:
    out: List[str] = [INTRO]
    out.append(f'## Rules ({len(rules)})')
    out.append('')
    out.append('| File | Last updated (UTC) | Description |')
    out.append('|---|---|---|')
    for p in rules:
        out.append(row(p, 'rule'))
    out.append('')
    out.append(f'## Skills ({len(skills)})')
    out.append('')
    out.append('| Skill | Last updated (UTC) | Description |')
    out.append('|---|---|---|')
    for p in skills:
        out.append(row(p, 'skill'))
    out.append('')
    out.append(f'## Subagents ({len(agents)})')
    out.append('')
    out.append('| Agent | Last updated (UTC) | Description |')
    out.append('|---|---|---|')
    for p in agents:
        out.append(row(p, 'agent'))
    out.append('')
    return '\n'.join(out)


Path(OUTPUT).write_text(render())
print(f"Wrote {OUTPUT} ({len(rules)} rules + {len(skills)} skills + {len(agents)} agents = {len(rules) + len(skills) + len(agents)} entries)")
PYEOF
